/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SelecoesRouteImport } from './routes/selecoes'
import { Route as PeneirasRouteImport } from './routes/peneiras'
import { Route as NovoJogoRouteImport } from './routes/novo-jogo'
import { Route as NegociacoesRouteImport } from './routes/negociacoes'
import { Route as MundoRouteImport } from './routes/mundo'
import { Route as JogadorRouteImport } from './routes/jogador'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as EmpresarioRouteImport } from './routes/empresario'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CompeticoesRouteImport } from './routes/competicoes'
import { Route as CarreirasRouteImport } from './routes/carreiras'
import { Route as CarreiraRouteImport } from './routes/carreira'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MundoIndexRouteImport } from './routes/mundo.index'
import { Route as MundoCompeticaoCompetitionSlugRouteImport } from './routes/mundo.competicao.$competitionSlug'
import { Route as MundoClubeClubSlugRouteImport } from './routes/mundo.clube.$clubSlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SelecoesRoute = SelecoesRouteImport.update({
  id: '/selecoes',
  path: '/selecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PeneirasRoute = PeneirasRouteImport.update({
  id: '/peneiras',
  path: '/peneiras',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoJogoRoute = NovoJogoRouteImport.update({
  id: '/novo-jogo',
  path: '/novo-jogo',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociacoesRoute = NegociacoesRouteImport.update({
  id: '/negociacoes',
  path: '/negociacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MundoRoute = MundoRouteImport.update({
  id: '/mundo',
  path: '/mundo',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadorRoute = JogadorRouteImport.update({
  id: '/jogador',
  path: '/jogador',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresarioRoute = EmpresarioRouteImport.update({
  id: '/empresario',
  path: '/empresario',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CompeticoesRoute = CompeticoesRouteImport.update({
  id: '/competicoes',
  path: '/competicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreirasRoute = CarreirasRouteImport.update({
  id: '/carreiras',
  path: '/carreiras',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreiraRoute = CarreiraRouteImport.update({
  id: '/carreira',
  path: '/carreira',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MundoIndexRoute = MundoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MundoRoute,
} as any)
const MundoCompeticaoCompetitionSlugRoute =
  MundoCompeticaoCompetitionSlugRouteImport.update({
    id: '/competicao/$competitionSlug',
    path: '/competicao/$competitionSlug',
    getParentRoute: () => MundoRoute,
  } as any)
const MundoClubeClubSlugRoute = MundoClubeClubSlugRouteImport.update({
  id: '/clube/$clubSlug',
  path: '/clube/$clubSlug',
  getParentRoute: () => MundoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carreira': typeof CarreiraRoute
  '/carreiras': typeof CarreirasRoute
  '/competicoes': typeof CompeticoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/creditos': typeof CreditosRoute
  '/empresario': typeof EmpresarioRoute
  '/historico': typeof HistoricoRoute
  '/jogador': typeof JogadorRoute
  '/mundo': typeof MundoRouteWithChildren
  '/negociacoes': typeof NegociacoesRoute
  '/novo-jogo': typeof NovoJogoRoute
  '/peneiras': typeof PeneirasRoute
  '/selecoes': typeof SelecoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/mundo/': typeof MundoIndexRoute
  '/mundo/clube/$clubSlug': typeof MundoClubeClubSlugRoute
  '/mundo/competicao/$competitionSlug': typeof MundoCompeticaoCompetitionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carreira': typeof CarreiraRoute
  '/carreiras': typeof CarreirasRoute
  '/competicoes': typeof CompeticoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/creditos': typeof CreditosRoute
  '/empresario': typeof EmpresarioRoute
  '/historico': typeof HistoricoRoute
  '/jogador': typeof JogadorRoute
  '/negociacoes': typeof NegociacoesRoute
  '/novo-jogo': typeof NovoJogoRoute
  '/peneiras': typeof PeneirasRoute
  '/selecoes': typeof SelecoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/mundo': typeof MundoIndexRoute
  '/mundo/clube/$clubSlug': typeof MundoClubeClubSlugRoute
  '/mundo/competicao/$competitionSlug': typeof MundoCompeticaoCompetitionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carreira': typeof CarreiraRoute
  '/carreiras': typeof CarreirasRoute
  '/competicoes': typeof CompeticoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/creditos': typeof CreditosRoute
  '/empresario': typeof EmpresarioRoute
  '/historico': typeof HistoricoRoute
  '/jogador': typeof JogadorRoute
  '/mundo': typeof MundoRouteWithChildren
  '/negociacoes': typeof NegociacoesRoute
  '/novo-jogo': typeof NovoJogoRoute
  '/peneiras': typeof PeneirasRoute
  '/selecoes': typeof SelecoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/mundo/': typeof MundoIndexRoute
  '/mundo/clube/$clubSlug': typeof MundoClubeClubSlugRoute
  '/mundo/competicao/$competitionSlug': typeof MundoCompeticaoCompetitionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carreira'
    | '/carreiras'
    | '/competicoes'
    | '/configuracoes'
    | '/creditos'
    | '/empresario'
    | '/historico'
    | '/jogador'
    | '/mundo'
    | '/negociacoes'
    | '/novo-jogo'
    | '/peneiras'
    | '/selecoes'
    | '/sitemap.xml'
    | '/mundo/'
    | '/mundo/clube/$clubSlug'
    | '/mundo/competicao/$competitionSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carreira'
    | '/carreiras'
    | '/competicoes'
    | '/configuracoes'
    | '/creditos'
    | '/empresario'
    | '/historico'
    | '/jogador'
    | '/negociacoes'
    | '/novo-jogo'
    | '/peneiras'
    | '/selecoes'
    | '/sitemap.xml'
    | '/mundo'
    | '/mundo/clube/$clubSlug'
    | '/mundo/competicao/$competitionSlug'
  id:
    | '__root__'
    | '/'
    | '/carreira'
    | '/carreiras'
    | '/competicoes'
    | '/configuracoes'
    | '/creditos'
    | '/empresario'
    | '/historico'
    | '/jogador'
    | '/mundo'
    | '/negociacoes'
    | '/novo-jogo'
    | '/peneiras'
    | '/selecoes'
    | '/sitemap.xml'
    | '/mundo/'
    | '/mundo/clube/$clubSlug'
    | '/mundo/competicao/$competitionSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarreiraRoute: typeof CarreiraRoute
  CarreirasRoute: typeof CarreirasRoute
  CompeticoesRoute: typeof CompeticoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CreditosRoute: typeof CreditosRoute
  EmpresarioRoute: typeof EmpresarioRoute
  HistoricoRoute: typeof HistoricoRoute
  JogadorRoute: typeof JogadorRoute
  MundoRoute: typeof MundoRouteWithChildren
  NegociacoesRoute: typeof NegociacoesRoute
  NovoJogoRoute: typeof NovoJogoRoute
  PeneirasRoute: typeof PeneirasRoute
  SelecoesRoute: typeof SelecoesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selecoes': {
      id: '/selecoes'
      path: '/selecoes'
      fullPath: '/selecoes'
      preLoaderRoute: typeof SelecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peneiras': {
      id: '/peneiras'
      path: '/peneiras'
      fullPath: '/peneiras'
      preLoaderRoute: typeof PeneirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-jogo': {
      id: '/novo-jogo'
      path: '/novo-jogo'
      fullPath: '/novo-jogo'
      preLoaderRoute: typeof NovoJogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negociacoes': {
      id: '/negociacoes'
      path: '/negociacoes'
      fullPath: '/negociacoes'
      preLoaderRoute: typeof NegociacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mundo': {
      id: '/mundo'
      path: '/mundo'
      fullPath: '/mundo'
      preLoaderRoute: typeof MundoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogador': {
      id: '/jogador'
      path: '/jogador'
      fullPath: '/jogador'
      preLoaderRoute: typeof JogadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresario': {
      id: '/empresario'
      path: '/empresario'
      fullPath: '/empresario'
      preLoaderRoute: typeof EmpresarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competicoes': {
      id: '/competicoes'
      path: '/competicoes'
      fullPath: '/competicoes'
      preLoaderRoute: typeof CompeticoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreiras': {
      id: '/carreiras'
      path: '/carreiras'
      fullPath: '/carreiras'
      preLoaderRoute: typeof CarreirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreira': {
      id: '/carreira'
      path: '/carreira'
      fullPath: '/carreira'
      preLoaderRoute: typeof CarreiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mundo/': {
      id: '/mundo/'
      path: '/'
      fullPath: '/mundo/'
      preLoaderRoute: typeof MundoIndexRouteImport
      parentRoute: typeof MundoRoute
    }
    '/mundo/competicao/$competitionSlug': {
      id: '/mundo/competicao/$competitionSlug'
      path: '/competicao/$competitionSlug'
      fullPath: '/mundo/competicao/$competitionSlug'
      preLoaderRoute: typeof MundoCompeticaoCompetitionSlugRouteImport
      parentRoute: typeof MundoRoute
    }
    '/mundo/clube/$clubSlug': {
      id: '/mundo/clube/$clubSlug'
      path: '/clube/$clubSlug'
      fullPath: '/mundo/clube/$clubSlug'
      preLoaderRoute: typeof MundoClubeClubSlugRouteImport
      parentRoute: typeof MundoRoute
    }
  }
}

interface MundoRouteChildren {
  MundoIndexRoute: typeof MundoIndexRoute
  MundoClubeClubSlugRoute: typeof MundoClubeClubSlugRoute
  MundoCompeticaoCompetitionSlugRoute: typeof MundoCompeticaoCompetitionSlugRoute
}

const MundoRouteChildren: MundoRouteChildren = {
  MundoIndexRoute: MundoIndexRoute,
  MundoClubeClubSlugRoute: MundoClubeClubSlugRoute,
  MundoCompeticaoCompetitionSlugRoute: MundoCompeticaoCompetitionSlugRoute,
}

const MundoRouteWithChildren = MundoRoute._addFileChildren(MundoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarreiraRoute: CarreiraRoute,
  CarreirasRoute: CarreirasRoute,
  CompeticoesRoute: CompeticoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CreditosRoute: CreditosRoute,
  EmpresarioRoute: EmpresarioRoute,
  HistoricoRoute: HistoricoRoute,
  JogadorRoute: JogadorRoute,
  MundoRoute: MundoRouteWithChildren,
  NegociacoesRoute: NegociacoesRoute,
  NovoJogoRoute: NovoJogoRoute,
  PeneirasRoute: PeneirasRoute,
  SelecoesRoute: SelecoesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
